version: '3.4'

services:
  frontend:
    image: ${DOCKER_REGISTRY-}frontend
    build:
      context: .
      dockerfile: FrontEnd/Dockerfile
    depends_on:
    - backend

  backend:
    image: ${DOCKER_REGISTRY-}backend
    build:
      context: .
      dockerfile: BackEnd/Dockerfile
    depends_on:
    - db

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment: 
        SA_PASSWORD: "Your_password123"
        ACCEPT_EULA: "Y"
    ports:
     - 1433:1433