version: '3.4'

services:
  frontend:
    image: ${DOCKER_REGISTRY-}frontend
    build:
      context: .
      dockerfile: FrontEnd/Dockerfile
    depends_on:
    - backend
    ports:
    - 8000:80
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment: 
        SA_PASSWORD: "1Secure*Password1"
        ACCEPT_EULA: "Y"
    volumes:
    - sqlvolume:/var/opt/mssql

  backend:
    image: ${DOCKER_REGISTRY-}backend
    build:
      context: .
      dockerfile: BackEnd/Dockerfile
    depends_on:
    - db

volumes:
 sqlvolume: {}
